export type DiscoverTopic = 'technology' | 'software' | 'design' | 'science' | 'curiosity';

export interface DiscoverCard {
  id: string;
  topic: DiscoverTopic;
  title: string;
  summary: string;
  insight: string;
  minutes: number;
}

export const DISCOVER_TOPIC_LABELS: Record<DiscoverTopic, string> = {
  technology: 'Everyday technology',
  software: 'Software made understandable',
  design: 'Interface and product design',
  science: 'Everyday science',
  curiosity: 'Small curiosities',
};

export const DISCOVER_CARDS: DiscoverCard[] = [
  {
    id: 'qr-error-correction',
    topic: 'technology',
    title: 'How QR codes survive scratches',
    summary: 'QR codes repeat enough information that a scanner can reconstruct sections hidden by dirt, damage, or a logo.',
    insight: 'Their error-correction level trades storage capacity for resilience, while the three large corner markers help the camera recover orientation.',
    minutes: 1,
  },
  {
    id: 'after-tapping-link',
    topic: 'technology',
    title: 'What happens after you tap a link',
    summary: 'A browser resolves a name, establishes an encrypted connection, requests a document, and assembles many resources into one page.',
    insight: 'Most pages require several network round trips, so latency and dependency ordering can matter more than raw download speed.',
    minutes: 2,
  },
  {
    id: 'gps-timing',
    topic: 'technology',
    title: 'How GPS finds you',
    summary: 'A phone estimates its distance from multiple satellites by comparing when their precisely timed radio signals arrive.',
    insight: 'The receiver solves for latitude, longitude, altitude, and its own imperfect clock at the same time, which is why four satellites are especially useful.',
    minutes: 2,
  },
  {
    id: 'noise-cancellation',
    topic: 'technology',
    title: 'How noise cancellation removes sound',
    summary: 'Headphones listen to surrounding noise and play a rapidly calculated waveform designed to oppose it.',
    insight: 'The technique works best on predictable low-frequency sounds such as engines; sudden voices and sharp noises are harder to cancel before they arrive.',
    minutes: 1,
  },
  {
    id: 'touchscreen-capacitance',
    topic: 'technology',
    title: 'How a touchscreen detects your finger',
    summary: 'A transparent grid senses tiny changes in an electrical field when a conductive finger approaches the glass.',
    insight: 'The controller combines changes across neighboring grid points to estimate position and distinguish several simultaneous touches.',
    minutes: 1,
  },
  {
    id: 'battery-aging',
    topic: 'technology',
    title: 'Why phone batteries gradually weaken',
    summary: 'Charging and discharging slowly changes the battery chemistry and reduces the amount of lithium that can move usefully.',
    insight: 'Heat and long periods at extreme charge levels accelerate this aging, while modern charging systems try to limit the most damaging conditions.',
    minutes: 2,
  },
  {
    id: 'video-buffering',
    topic: 'technology',
    title: 'Why videos buffer on fast internet',
    summary: 'A high speed test cannot guarantee that every server, route, radio link, and momentary queue can deliver video consistently.',
    insight: 'Players maintain a buffer and adapt quality because stable delivery matters more than occasional bursts of very high bandwidth.',
    minutes: 1,
  },
  {
    id: 'image-compression',
    topic: 'technology',
    title: 'How image compression removes data',
    summary: 'Lossy formats represent broad visual patterns efficiently and discard fine differences people are less likely to notice.',
    insight: 'Repeated editing and saving can expose the discarded structure as blockiness, ringing, or blurred detail around strong edges.',
    minutes: 2,
  },
  {
    id: 'incognito-boundaries',
    topic: 'technology',
    title: 'What Incognito Mode actually protects',
    summary: 'Private browsing mainly avoids keeping local history, cookies, and form data after the private window closes.',
    insight: 'Websites, employers, internet providers, and network administrators can still observe traffic according to their access and policies.',
    minutes: 1,
  },
  {
    id: 'airplane-mode',
    topic: 'technology',
    title: 'Why airplane mode can still allow Wi-Fi',
    summary: 'Airplane mode disables selected radios as a group, but modern phones let users turn approved local radios back on individually.',
    insight: 'Cellular, Wi-Fi, Bluetooth, GPS reception, and near-field communication are separate systems even when one shortcut controls several of them.',
    minutes: 1,
  },
  {
    id: 'git-commit-snapshot',
    topic: 'software',
    title: 'What a Git commit really stores',
    summary: 'A commit identifies a complete project snapshot, its parent commit or commits, author information, time, and message.',
    insight: 'Git efficiently reuses identical file objects, so thinking in snapshots does not mean every commit stores a full duplicate of the repository.',
    minutes: 2,
  },
  {
    id: 'works-on-my-machine',
    topic: 'software',
    title: 'Why “works on my machine” happens',
    summary: 'Software behavior depends on versions, configuration, data, permissions, locale, clocks, networks, and many other environmental details.',
    insight: 'Reproducible builds, explicit dependencies, containers, and production-like tests reduce the number of assumptions hidden on one developer’s computer.',
    minutes: 2,
  },
  {
    id: 'terminal-enter',
    topic: 'software',
    title: 'What happens when you press Enter in a terminal',
    summary: 'The shell parses the command, expands variables and patterns, connects input and output, and asks the operating system to start programs.',
    insight: 'Pipes are not visual decoration: they connect one process’s output stream directly to another process’s input stream.',
    minutes: 2,
  },
  {
    id: 'cache-tradeoff',
    topic: 'software',
    title: 'Why caches make systems fast and strange',
    summary: 'A cache avoids repeating expensive work by keeping a nearby copy of a previous result.',
    insight: 'The difficult question is invalidation: deciding exactly when the stored answer is no longer safe to reuse.',
    minutes: 1,
  },
  {
    id: 'encryption-hashing',
    topic: 'software',
    title: 'Encryption versus hashing',
    summary: 'Encryption protects information with a key so an authorized party can recover it; hashing creates a one-way fingerprint.',
    insight: 'Password systems typically store slow salted hashes so verification is possible without keeping the original password.',
    minutes: 2,
  },
  {
    id: 'api-contract',
    topic: 'software',
    title: 'What an API is in plain language',
    summary: 'An API is an agreed vocabulary and set of rules that lets one piece of software ask another to do something.',
    insight: 'A stable API hides implementation detail, allowing the provider to change its internals without forcing every consumer to change.',
    minutes: 1,
  },
  {
    id: 'database-index',
    topic: 'software',
    title: 'How a database index works',
    summary: 'An index maintains an additional ordered structure that helps the database locate matching rows without scanning everything.',
    insight: 'Indexes accelerate reads but consume storage and add work to inserts and updates, so more indexes are not automatically better.',
    minutes: 2,
  },
  {
    id: 'idempotent-retries',
    topic: 'software',
    title: 'Why retries can duplicate actions',
    summary: 'A client may retry after losing a response even though the original request already succeeded on the server.',
    insight: 'Idempotency keys let the server recognize the repeated intent and return the original result instead of charging or creating twice.',
    minutes: 2,
  },
  {
    id: 'race-condition',
    topic: 'software',
    title: 'What a race condition looks like',
    summary: 'Two individually correct operations can produce an incorrect result when their steps overlap in an unexpected order.',
    insight: 'Locks, transactions, queues, immutable data, and carefully designed ownership rules are different ways to control that ordering.',
    minutes: 2,
  },
  {
    id: 'flaky-tests',
    topic: 'software',
    title: 'Why tests become flaky',
    summary: 'Tests become unreliable when they depend on real clocks, shared state, network timing, random ordering, or incomplete cleanup.',
    insight: 'The right fix is to control or observe the hidden dependency, not to weaken the assertion or repeat the test until it happens to pass.',
    minutes: 2,
  },
  {
    id: 'progress-indicators',
    topic: 'design',
    title: 'Why progress indicators reduce anxiety',
    summary: 'People tolerate waiting better when the interface confirms that work continues and gives a credible sense of what remains.',
    insight: 'A truthful stage label can be more reassuring than a fake percentage whose speed changes unpredictably.',
    minutes: 1,
  },
  {
    id: 'skeleton-screens',
    topic: 'design',
    title: 'Why skeleton screens feel faster',
    summary: 'A skeleton reveals the shape of incoming content immediately instead of presenting a blank surface with no spatial expectations.',
    insight: 'It works best when the skeleton closely matches the final layout; otherwise the later movement creates distraction rather than continuity.',
    minutes: 1,
  },
  {
    id: 'undo-over-confirmation',
    topic: 'design',
    title: 'Why Undo can beat repeated confirmation',
    summary: 'Recoverable actions can proceed quickly when the interface makes reversal obvious and reliable.',
    insight: 'Confirmation remains appropriate when an action is irreversible, costly, legally meaningful, or difficult to explain after the fact.',
    minutes: 2,
  },
  {
    id: 'visual-hierarchy',
    topic: 'design',
    title: 'Why one clear button often beats five equal buttons',
    summary: 'Visual hierarchy helps people identify the expected next step without reading every control with equal attention.',
    insight: 'Secondary actions still need to remain discoverable, but they should not compete with the action most users came to perform.',
    minutes: 1,
  },
  {
    id: 'notification-fatigue',
    topic: 'design',
    title: 'Why people stop noticing notifications',
    summary: 'Repeated low-value interruptions train people to dismiss the entire channel, including the rare important message.',
    insight: 'Good notification systems reserve urgency for events that are timely, actionable, and meaningfully improved by interruption.',
    minutes: 2,
  },
  {
    id: 'haptic-language',
    topic: 'design',
    title: 'What good haptic feedback communicates',
    summary: 'A short physical response can confirm selection, boundaries, errors, or completion without adding another visual element.',
    insight: 'Patterns should stay restrained and consistent because strong or frequent vibration quickly becomes unpleasant and loses meaning.',
    minutes: 1,
  },
  {
    id: 'dark-mode-reading',
    topic: 'design',
    title: 'Why dark mode is not always easier to read',
    summary: 'Comfort depends on ambient light, contrast, text weight, display quality, vision, and the amount of content being read.',
    insight: 'Supporting both themes and preserving strong contrast is more inclusive than assuming one palette is universally superior.',
    minutes: 1,
  },
  {
    id: 'power-of-defaults',
    topic: 'design',
    title: 'How defaults quietly shape decisions',
    summary: 'Many users accept the preselected option because changing it requires attention, confidence, and an expectation of benefit.',
    insight: 'Defaults therefore carry ethical weight: they should represent a safe, broadly suitable choice rather than the provider’s most profitable outcome.',
    minutes: 2,
  },
  {
    id: 'destructive-friction',
    topic: 'design',
    title: 'Why destructive actions need friction',
    summary: 'The interaction cost of an action should roughly reflect the consequence of making it accidentally.',
    insight: 'Clear labels, spatial separation, reversible soft deletion, and targeted confirmation are better than making every ordinary action cumbersome.',
    minutes: 1,
  },
  {
    id: 'endless-spinner',
    topic: 'design',
    title: 'Why an endless spinner feels broken',
    summary: 'A spinner confirms animation, but it does not explain the task, expected duration, progress, or whether recovery is possible.',
    insight: 'After a short grace period, useful interfaces reveal the current stage and provide a safe retry, cancellation, or diagnostic path.',
    minutes: 1,
  },
  {
    id: 'blue-sky-red-sunset',
    topic: 'science',
    title: 'Why the sky is blue and sunsets are red',
    summary: 'Air molecules scatter shorter visible wavelengths more strongly, filling the daytime sky with blue light.',
    insight: 'Near sunset, sunlight travels through more atmosphere, scattering much of the blue away before the remaining orange and red light reaches you.',
    minutes: 2,
  },
  {
    id: 'metal-feels-colder',
    topic: 'science',
    title: 'Why metal feels colder than wood',
    summary: 'Objects at the same room temperature can feel different because metal carries heat away from your skin much faster.',
    insight: 'Your temperature receptors respond to the rate of heat transfer, not merely to the object’s measured temperature.',
    minutes: 1,
  },
  {
    id: 'soap-and-grease',
    topic: 'science',
    title: 'How soap removes grease',
    summary: 'Soap molecules have one end attracted to water and another attracted to oils and fats.',
    insight: 'They surround grease in tiny structures that let flowing water carry material it could not dissolve on its own.',
    minutes: 1,
  },
  {
    id: 'microwave-hot-spots',
    topic: 'science',
    title: 'Why microwaves create hot and cold spots',
    summary: 'Reflected microwaves interfere inside the oven and form regions where electromagnetic energy is stronger or weaker.',
    insight: 'The rotating tray moves food through those regions, while resting time lets heat spread from hotter areas into cooler ones.',
    minutes: 2,
  },
  {
    id: 'moon-horizon-illusion',
    topic: 'science',
    title: 'Why the Moon looks larger near the horizon',
    summary: 'The Moon’s image on the eye is nearly the same size, but surrounding landscape cues change how the brain interprets it.',
    insight: 'A simple photograph or a view through a small tube removes many contextual cues and makes the apparent enlargement less dramatic.',
    minutes: 1,
  },
  {
    id: 'mirror-direction',
    topic: 'science',
    title: 'Why mirrors do not really reverse left and right',
    summary: 'A mirror reverses the direction perpendicular to its surface: front becomes back.',
    insight: 'Left and right seem exchanged because we imagine rotating ourselves to face the same direction as the reflected person.',
    minutes: 1,
  },
  {
    id: 'camera-screen-flicker',
    topic: 'science',
    title: 'Why cameras sometimes see screens flicker',
    summary: 'Displays refresh and lights pulse rapidly while cameras expose or scan an image over their own timing interval.',
    insight: 'When those rhythms do not align, the recording can show dark bands or flicker that human vision had blended together.',
    minutes: 1,
  },
  {
    id: 'ice-floats',
    topic: 'science',
    title: 'Why ice floats instead of sinking',
    summary: 'Water molecules form an open crystal structure when freezing, taking up more space for the same amount of matter.',
    insight: 'That lower density makes ice float and lets lakes freeze from the surface downward, insulating liquid water below.',
    minutes: 2,
  },
  {
    id: 'spice-feels-hot',
    topic: 'science',
    title: 'Why spicy food feels hot',
    summary: 'Capsaicin activates receptors that normally respond to potentially damaging heat.',
    insight: 'The tissue is not necessarily hotter, but the nervous system receives a familiar warning signal and produces sweating and flushing.',
    minutes: 1,
  },
  {
    id: 'smell-and-memory',
    topic: 'science',
    title: 'Why smells trigger vivid memories',
    summary: 'Smell-processing pathways have unusually direct connections with brain regions involved in emotion and memory.',
    insight: 'A familiar scent can therefore retrieve an old scene with an emotional immediacy that feels different from deliberate recall.',
    minutes: 2,
  },
  {
    id: 'timezone-borders',
    topic: 'curiosity',
    title: 'Why time-zone borders zigzag',
    summary: 'Time zones follow political borders, trade relationships, population centers, and practical routines more often than perfect longitude lines.',
    insight: 'Governments can change them, which means software needs frequently updated time-zone data rather than a permanent mathematical formula.',
    minutes: 2,
  },
  {
    id: 'leap-years',
    topic: 'curiosity',
    title: 'Why leap years exist',
    summary: 'Earth’s trip around the Sun does not take a whole number of days, so calendars need periodic correction.',
    insight: 'The Gregorian rule skips some century leap years but keeps those divisible by 400, producing a close long-term approximation.',
    minutes: 1,
  },
  {
    id: 'map-distortion',
    topic: 'curiosity',
    title: 'Why every flat world map is distorted',
    summary: 'Flattening a sphere requires stretching, tearing, or compressing some combination of shape, area, distance, or direction.',
    insight: 'Different projections preserve different properties, so the right map depends on whether the task is navigation, comparison, education, or display.',
    minutes: 2,
  },
  {
    id: 'barcode-structure',
    topic: 'curiosity',
    title: 'How barcode scanners recognize lines',
    summary: 'A scanner measures alternating reflections from dark bars and light spaces, then interprets their relative widths.',
    insight: 'Guard patterns identify orientation and boundaries, while a check digit helps detect common reading or typing errors.',
    minutes: 2,
  },
  {
    id: 'qwerty-history',
    topic: 'curiosity',
    title: 'Why keyboards use QWERTY',
    summary: 'The layout developed alongside early mechanical typewriters and spread through training, manufacturing, and institutional adoption.',
    insight: 'Once a standard accumulates users, habits, documentation, and compatible products, replacing it can cost more than its imperfections.',
    minutes: 2,
  },
  {
    id: 'rounded-airplane-windows',
    topic: 'curiosity',
    title: 'Why airplane windows have rounded corners',
    summary: 'Sharp corners concentrate mechanical stress, especially when a pressurized cabin repeatedly expands and contracts.',
    insight: 'Rounded openings distribute forces more smoothly and reduce the chance that small cracks grow from one highly stressed point.',
    minutes: 1,
  },
  {
    id: 'road-mirage',
    topic: 'curiosity',
    title: 'Why roads can look wet on hot days',
    summary: 'Air close to a hot road can be much warmer and less dense than the air above it, bending light along a curved path.',
    insight: 'Your brain interprets light arriving from near the ground as a reflection, producing the appearance of distant water.',
    minutes: 1,
  },
  {
    id: 'static-shock',
    topic: 'curiosity',
    title: 'Why a doorknob can give you a shock',
    summary: 'Friction can move electrons between materials and leave your body with an electrical imbalance.',
    insight: 'A metal object provides a sudden conductive path, equalizing the charge quickly enough to produce a tiny spark and sharp sensation.',
    minutes: 1,
  },
  {
    id: 'popcorn-pops',
    topic: 'curiosity',
    title: 'Why popcorn pops',
    summary: 'Water trapped inside the kernel becomes pressurized steam while the hard outer shell initially contains it.',
    insight: 'When the shell ruptures, pressure drops, softened starch expands rapidly, and the kernel turns inside out into a foam.',
    minutes: 1,
  },
  {
    id: 'cat-righting-reflex',
    topic: 'curiosity',
    title: 'How cats rotate while falling',
    summary: 'A cat bends its body so the front and rear halves can rotate with different effective moments of inertia.',
    insight: 'By changing shape through the maneuver, it can reorient without needing to push against the air, though falling is still dangerous.',
    minutes: 2,
  },
];

if (DISCOVER_CARDS.length !== 50) {
  throw new Error(`Expected 50 Discover cards, found ${DISCOVER_CARDS.length}.`);
}
